artifacts_root: artifacts
model_root: model

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1zgK9fvdzyTCC7cwn6RlNmbJNk03zcBD3/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  trained_model_path_in_use: model/model.h5
